//
// Created by Viktor Hundahl Strate on 14/10/2017.
//

#ifndef LIDARROBOT_PINSETUP_H
#define LIDARROBOT_PINSETUP_H

#include <Arduino.h>

// Motor pins
#define MOTOR_RIGHT_FORWARD 8
#define MOTOR_RIGHT_BACKWARDS 7

#define MOTOR_LEFT_FORWARD 9
#define MOTOR_LEFT_BACKWARDS 4

#define MOTOR_SPEED_RIGHT 6
#define MOTOR_SPEED_LEFT 5

#define MOTOR_CURRENT_SENSOR_LEFT A2
#define MOTOR_CURRENT_SENSOR_RIGHT A3

#define ENABLE_MOTOR_LEFT A0
#define ENABLE_MOTOR_RIGHT A1

// Remote control
#define RC_LEFT_UP 11
#define RC_LEFT_RIGHT 10
#define RC_RIGHT_UP 12
#define RC_RIGHT_RIGHT 13

#endif //LIDARROBOT_PINSETUP_H
